Feature/connect filters to bills fetch
sunrisemvmtnyc/legislation-tracker pull request #32
Opened 2024-04-15 16:08 UTC by derekmiranda

have a rough implementation of applying the elasticsearch term to the bills API call

though could use help in refining how to format the term since the search either returns every bill as if there were no filters, or no bills

2024-04-17 17:40 UTC, elliott-king requested changes
> though could use help in refining how to format the term since the search either returns every bill as if there were no filters, or no bills

"legislator name" works out-of-the-box for me, and I made a suggested change to fix "bill status"

Some addtl requests:

The filter background should be darker if option is selected. It's hard to tell if multiple are selected - we can ask for design, or you can do.

Can you install [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) so this is formatted like everything else?

In my workspace settings:
```
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true,
    },
```

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/constants.js
> +  STATUS: 'status.statusdesc',
```suggestion
  STATUS: 'status.statusDesc',
```

Not working for me otherwise.

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/components/HomePage/Filters.jsx
> +    </div>
NOTE: this isn't filtering anything, but I assume that's intentional.

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/components/HomePage/Filters.jsx
> +        options={[
```suggestion
        // TODO: placeholder
        options={[
```

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/utils.js
> +export function createQueryStr(params) {
IMO this should not be a helper fn. Just inline `new URLSearchParams({ offset, term: searchTerm }).toString()` in `index.jsx`

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/components/HomePage/index.jsx
> +  const [searchTerm, setSearchTerm] = useState('');
```suggestion
  const [searchTerm, setSearchTerm] = useState('*');
```

Since the default in `Filters.jsx` is `"*"`

2024-04-17 17:40 UTC, elliott-king commented on frontend/src/components/HomePage/Filters.jsx
> +  setSearchTerm: PropTypes.func,
```suggestion
  setSearchTerm: PropTypes.func.isRequired,
```

2024-05-03 19:27 UTC, derekmiranda commented
> > though could use help in refining how to format the term since the search either returns every bill as if there were no filters, or no bills
> 
> "legislator name" works out-of-the-box for me, and I made a suggested change to fix "bill status"
> 
> Some addtl requests:
> 
> The filter background should be darker if option is selected. It's hard to tell if multiple are selected - we can ask for design, or you can do.
> 
> Can you install [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) so this is formatted like everything else?
> 
> In my workspace settings:
> 
> ```
>     "[javascript]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode",
>         "editor.formatOnSave": true,
>     },
> ```

@elliott-king i've got the selected MenuItem darkened in another PR comin up so just wanted to check if this PR is good to go

2024-05-20 13:52 UTC, elliott-king approved these changes
LGTM

2024-05-22 02:01 UTC, merged